version: "3"
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    hostname: mongodb
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./docker-resources/mongodb:/nearshops
    ports:
      - 27017:27017
    command: bash /nearshops/bootstrap.sh
    networks:
      - nearshops_net

  apigateway:
    build: api_gateway/.
    image: nearshops/api_gateway
    container_name: apigateway
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 500M
      restart_policy:
        condition: on-failure
    environment:
      APP_BIND: '0.0.0.0'
      APP_PORT: 80
      API_BIND: '{"shops":"http://shopservice","auth": "http://authservice"}'
    ports:
      - 5002:80
    networks:
      - nearshops_net
    links:
      - shopservice
      - authservice

  authservice:
    build: authentication_service/.
    image: nearshops/auth_service
    container_name: authservice
    hostname: authservice
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 500M
      restart_policy:
        condition: on-failure
    environment:
      APP_BIND: '0.0.0.0'
      APP_PORT: 80
      MONGO_URI: 'mongodb://shopproxy:azerty@mongodb:27017/'
      AUTH_HOST: 'authservice'
    networks:
      - nearshops_net
    depends_on:
      - mongodb

  shopservice:
    build: shop_service/.
    image: nearshops/shop_service
    container_name: shopservice
    hostname: shopservice
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 500M
      restart_policy:
        condition: on-failure
    environment:
      - APP_BIND=0.0.0.0
      - APP_PORT=80
      - MONGO_URI=mongodb://shopproxy:azerty@mongodb:27017/
      - AUTH_HOST=authservice
    networks:
      - nearshops_net
    depends_on:
      - mongodb

networks:
  nearshops_net:
